spring.application.name=bff-agendador-tarefas

usuario.url=localhost:8080/usuario
agendador-tarefas.url=localhost:8081/tarefas
notificacao.url=localhost:8082/email


cron.horario=0 0/5 * * * ?

server.port=8083

usuario.email=admin@admin.com
usuario.senha=1234

# Configurações do Feign
feign.client.config.default.connect-timeout=10000
feign.client.config.default.read-timeout=60000
feign.client.config.default.logger-level=full

# Ativa OkHttp globalmente (requer a dependência feign-okhttp no pom.xml)
feign.okhttp.enabled=true

# Desabilita o cliente HTTP Apache padrão (se estiver ativo)
feign.httpclient.enabled=false

# Configurações de logging para debug do Feign e client
logging.level.com.javanauta.bffagendadortarefas.infrastructure.client.TarefasClient=DEBUG
logging.level.feign=DEBUG
